print ('Twinkle, twinkle, little star,',end='\n')
print ('    How I wonder what you are!',end='\n')
print ('         Up above the world so high,',end='\n')
print ('         Like a diamond in the sky.',end='\n')
print ('Twinkle, twinkle, little star,',end='\n')
print ('    How I wonder what you are')